### ISSUE TITLE
su-binary fails to compile using AOSP 4.1.1_r1 (LOGx API updated)

### ISSUE THREAD

**Issue by r3n4ud** [ChainsDD/su-binary#11]
`./system/core/include/cutils/log.h` has changed in 4.1.1. When using su-binary in place of the bare `system/extras/su`, the compilation process failed on LOGx undefined errors.

**Comment by git-core** [comment]
This issue has been fixed in the gc branch in slightly different way. See commit ffe8b01e0aaaa2676265fb3ab09657220a6310b8.
Considering your patch, it changes some parts that irrelevant of the issue. Did you make it intentionally?

**Comment by r3n4ud** [comment]
OK, the gc branch fix is for the best, I'll use that. The irrelevant parts of the commit are due to my emacs-tabs-are-evil-before-save-hook settings ;)

I'll close the issue but why don't merge the gc branch jb fix in the master branch or make the gc the default branch or document what exactly are those branch (I have browsed gc-ics but it didn't seem intuitive to me to have to browse the gc branch to find jb support).

Anyway, thanks for your quick response!
