### ISSUE TITLE
Version update 

### ISSUE THREAD

**Issue by PonsAsinorem** [ChainsDD/su-binary#5]
Version available through github is 3.0.1 while the version available through superuser is 3.0.3.

**Comment by ChainsDD** [comment]
Fixed, see commits:

https://github.com/ChainsDD/su-binary/commit/233b1d0aa95e8c43fd7f02b91ac047e2e32a8aa5 https://github.com/ChainsDD/su-binary/commit/447d6bde3ec0f89a71eadca545228662d5c937af

Version 3.0.1 and 3.0.3 are have the same code, the only difference was in the way it was built. Had some issues trying to figure out a new build system.
